### PR TITLE
Italian Postal Address Form, and support for Django 1.7

### PR DESCRIPTION
**Pull request by facconi**
I have:
* added the Italian Postal Address Form
* added the locale folder and created localization files for en (English) and it (Italian)
* imported json as simplejson if the import simplejson statement fails, to support Django 1.7 and the deprecation of simplejson
* fixed a typo: Germny is Germany
Hope this helps.

### CODE REVIEW

**Comment by facconi** [comment]
Added the locale folder and created localization files for en (English) and it (Italian).

**Comment by mthornhill** [comment]
Hi Francesco,
Thanks for this, I agree that we should remove the django-piston dependency, I'll have a look at this in the next couple of weeks. 
Thanks
Michael

**Comment by facconi** [comment]
Hi Michael. Thank you for the pull.
I really like your plugin and I'll try in the next days to help you to remove the django-piston dependency, if you'd like it.
Thanks

**Comment by mthornhill** [comment]
Hi Francesco,
That would be great, I'm on holidays at the moment, hence the non-release
of package.
If you submit a pull request to remove django-piston dependency, I'll
release a new version when I get home.
Thanks
Michael

On Tue, Feb 24, 2015 at 2:32 PM, Francesco Facconi <notifications@github.com
> wrote:

> Hi Michael. Thank you for the pull.
> I really like your plugin and I'll try in the next days to help you to
> remove the django-piston dependency, if you'd like it.
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mthornhill/django-postal/pull/19#issuecomment-75766402>
> .
>



-- 
p: +353 87 6124111
e: michael@maithu.com

**Pull request merged**
